services:
  useful-tools:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9002:3000"
    environment:
      - NODE_ENV=production
      - PG_HOST=172.17.0.1
      - PG_PORT=5432
      - PG_DATABASE=dashboard
      - PG_USER=postgres
      - PG_PASSWORD=postgres
